---
title: "Exercise 1"
author: "Przemysław Mazurek"
date: "8 04 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Exercise 1


## 1. A brief description of the show


_Once Upon a Time_ is an American fairy tale drama television series created by _Edward Kitsis_ and _Adam Horowitz_, who also serve as executive producers alongside _Steve Pearlman_. It debuted on _ABC_ on October 23, 2011. The first season introduces a bail bond agent, _Emma Swan_ (_Jennifer Morrison_) and her birth-son, _Henry Mills_ (_Jared S. Gilmore_), who discover that a New England town named _Storybrooke_, _Maine_ is actually a remnant of a parallel world that was cursed by _Henry's_ adoptive mother the _Evil Queen/Mayor Regina Mills_ (_Lana Parrilla_) and that all the characters from the fairy tales have no memories of who they were, including the parents of _Emma_: _Snow White/Mary Margaret Blanchard_ (_Ginnifer Goodwin_) and _Prince Charming/David Nolan_ (_Josh Dallas_), who sent her to the real world to save their world and break the curse.


